### ISSUE TITLE
About dataset 

### ISSUE THREAD

**Issue by zhgqcn** [jzsherlock4869/TISR_APTX4869#2]
- Why is it read as RGB when the thermal image is in grayscale? It appears that the RGB pattern is simply a repetition of the gray channel three times
- I wonder if this is done due to the input requirements of swinIR.

![image](https://github.com/jzsherlock4869/TISR_APTX4869/assets/44897668/d067c347-7edb-451d-bf58-a7aa0879c279)
![image](https://github.com/jzsherlock4869/TISR_APTX4869/assets/44897668/cc8819c4-a330-4260-8bd3-49552a52afaa)

**Comment by jzsherlock4869** [comment]
yes, 3-channel format is to comply with SwinIR input requirements to utilize the pretrained weights.
